spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3306/codelap}
    username: ${db.username:root}
    password: ${db.password:1234}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size : 100
        javax:
          persistence:
            validation:
              mode: none
        show-sql: true