env:
  DB_DATABASE: codelaptest
  DB_USER: root
  DB_PASSWORD: root

name: PR

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, edited ]

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{env.DB_DATABASE }};' -u${{env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -e 'SHOW DATABASES;' -uroot -proot

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Common Test
        run: ./gradlew common:test
        shell: bash

      - name: API Test
        run: ./gradlew api:test
        shell: bash
